version: "3.7"
services:
  app:
    build:
      args:
        user: halayon
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: gaapfc
    container_name: gaapfc-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      gaapfc:
        ipv4_address: 172.34.0.10

  db:
    image: mysql:5.7
    container_name: gaapfc-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      gaapfc:
        ipv4_address: 172.34.0.20

  nginx:
    image: nginx:1.15.2-alpine
    container_name: gaapfc-nginx
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      gaapfc:
        ipv4_address: 172.34.0.30
  cron:
    build:
      args:
        user: halayon
        uid: 1000
      context: ./docker-compose/php/
      dockerfile: Dockerfile
    image: php-cron
    container_name: gaapfc-crontab
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/php/crontab:/etc/crontab:ro
    command: bash -c "/usr/bin/crontab /etc/crontab && /usr/sbin/cron -f"
    networks:
      gaapfc:
        ipv4_address: 172.34.0.40
networks:
  gaapfc:
    driver: bridge
    ipam:
      config:
        - subnet: 172.34.0.0/24
volumes:
  dbdata:
    driver: local
