version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
      dockerfile: Dockerfile
    image: gaapfc
    container_name: gaapfc-app
    restart: unless-stopped
    ports:
      - ${HOST_PORT}:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      backend:
        ipv4_address: 172.35.0.10
        aliases:
          - app

  db:
    image: mysql:5.7
    container_name: gaapfc-db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.35.0.20
        aliases:
          - mysql-db
  cron:
    build:
      args:
        user: halayon
        uid:  ${UID}
      context: ./docker-compose/php/
      dockerfile: Dockerfile
    image: php-cron
    container_name: gaapfc-crontab
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/php/crontab:/etc/crontab:ro
    command: bash -c "/usr/bin/crontab /etc/crontab && /usr/sbin/cron -f"
    networks:
      backend:
        ipv4_address: 172.35.0.40

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/24
volumes:
  dbdata:
    driver: local